title: My Blog - v2.6
author:
  name: Penkey Suresh
  email: penkeysuresh@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Just implementation

show_excerpts: true # set to true to show excerpts on the homepage

permalink: /:title
baseurl: "v2.6"
# Minima date format
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: penkeysuresh
    github:  penkeysuresh

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
